package com.vinayappari.resumespringai.infrastructure;

import com.vinayappari.resumespringai.domain.DocumentExtractor;
import com.vinayappari.resumespringai.dto.ExtractionResponse;
import org.apache.tika.Tika;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.InputStream;

@Service
public class DocumentExtractionService implements DocumentExtractor {

    private final Tika tika;

    public DocumentExtractionService() {
        // Tika facade instance is thread-safe
        this.tika = new Tika();
    }

    @Override
    public ExtractionResponse extract(MultipartFile file) {
        try {
            // 1. Detect file type based on contents (magic bytes), not just file extension
            String fileType;
            try (InputStream streamForDetection = file.getInputStream()) {
                fileType = tika.detect(streamForDetection);
            }

            // 2. Extract plain text
            String text;
            try (InputStream streamForExtraction = file.getInputStream()) {
                text = tika.parseToString(streamForExtraction);
            }

            // Clean up the text (remove excessive newlines generated by Tika)
            String cleanText = text.replaceAll("\\s+", " ").trim();

            return new ExtractionResponse(fileType, cleanText);

        } catch (Exception e) {
            throw new RuntimeException("Failed to extract text from document: " + e.getMessage(), e);
        }
    }
}